on:
  - push
  - pull_request
name: build
jobs:
  go-pipeline:
    name: Go Checks
    strategy:
      matrix:
        version: [ 1.19 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: go${{ matrix.version }} linter
      continue-on-error: true
      uses: ./go${{ matrix.version }}/linter
      with:
        GOLINT: on
        MISSPELL: on
      env:
        PROJECT_PATH: test
    - name: go${{ matrix.version }} test
      uses: ./go${{ matrix.version }}/test
      continue-on-error: true
      env:
        PROJECT_PATH: test
